/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaVentas;

import ModeloVendedor.Vendedor;

/**
 *
 * @author ASUS
 */
public class frmPrincipal extends javax.swing.JFrame {

    private Vendedor vendedorActual;

    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public frmPrincipal(Vendedor vendedorLogueado) {
        initComponents();
        this.setLocationRelativeTo(null); // Para que aparezca centrado

        // Guardamos los datos del usuario que entró
        this.vendedorActual = vendedorLogueado;

        // Llamamos a la seguridad
        aplicarRestricciones();
    }

    private void aplicarRestricciones() {
        // Validamos si el que entró eres tú o Claudio
        if (vendedorActual.getRol().equalsIgnoreCase("Vendedor")) {

            // Ocultamos los botones de mantenimiento para que no puedan crear ni editar
            btnMantenimientoProductos.setVisible(false);
            btnMantenimientoClientes.setVisible(false);
            btnClientes.setVisible(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModuloVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnMantenimientoProductos = new javax.swing.JButton();
        btnMantenimientoClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModuloVentas.setText("Ir a Modulos de Ventas");
        btnModuloVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloVentasActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnMantenimientoProductos.setText("Añadir/Ver Productos");
        btnMantenimientoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoProductosActionPerformed(evt);
            }
        });

        btnMantenimientoClientes.setText("Añadir/Ver Clientes");
        btnMantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMantenimientoProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModuloVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClientes)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMantenimientoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModuloVentas)
                    .addComponent(btnClientes))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMantenimientoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMantenimientoClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloVentasActionPerformed
        frmVentas ventanaVentas = new frmVentas(vendedorActual);
        ventanaVentas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModuloVentasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        VistaClientes.frmClientes ventanaClientes = new VistaClientes.frmClientes(this, true);
        ventanaClientes.setLocationRelativeTo(this);
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnMantenimientoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoProductosActionPerformed
        VistaProductos.frmMantenimientoProductos mantProd = new VistaProductos.frmMantenimientoProductos();
        mantProd.setLocationRelativeTo(null);
        mantProd.setVisible(true);
    }//GEN-LAST:event_btnMantenimientoProductosActionPerformed

    private void btnMantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoClientesActionPerformed
        VistaClientes.frmMantenimientoClientes mantCli = new VistaClientes.frmMantenimientoClientes();
        mantCli.setLocationRelativeTo(null);
        mantCli.setVisible(true);
    }//GEN-LAST:event_btnMantenimientoClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    public void abrirModuloVentas() {
        // Le pasamos el vendedorActual que capturamos en el Login
        frmVentas ventanaVentas = new frmVentas(this.vendedorActual);
        ventanaVentas.setVisible(true);
        this.dispose(); // Cierra el menú principal
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnMantenimientoClientes;
    private javax.swing.JButton btnMantenimientoProductos;
    private javax.swing.JButton btnModuloVentas;
    private javax.swing.JButton btnRegresar;
    // End of variables declaration//GEN-END:variables
}
